### ISSUE TITLE
STM32 undefined reference to `TM1638_STB_OUTPUT'

### ISSUE THREAD

**Issue by P55-rgb** [MahdaSystem/TM1638#1]
Hello.
There are errors in the libraries!
Can you view my project or post your working project?

![image](https://user-images.githubusercontent.com/63473590/123727709-418ad180-d8bc-11eb-863b-565c7965e0fe.png)

c:\st\stm32cubeide_1.4.0\stm32cubeide\plugins\com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.9-2020-q2-update.win32_1.5.0.202011040924\tools\arm-none-eabi\bin\ld.exe: D:/ST_prog/tm1638my_pin/Debug/../Core/Src/TM1638_platform.c:135: undefined reference to `TM1638_STB_OUTPUT'

https://cloud.mail.ru/public/vb3r/BfCauUsco

**Comment by Hossein-M98** [comment]
Hello @P55-rgb
I checked your project. You must uncomment 55th line in "TM1638_platform.h" file.
![Annotation 2021-06-29 234542](https://user-images.githubusercontent.com/52778819/123854591-25c31200-d934-11eb-9391-677771be9b8f.png)

**Comment by P55-rgb** [comment]
![image](https://user-images.githubusercontent.com/63473590/124058649-f99eb280-da53-11eb-8dcc-6976efcb9978.png)
![image](https://user-images.githubusercontent.com/63473590/124058766-37034000-da54-11eb-929b-960cc12854de.png)

The project was assembled without errors.
1. Why is it not the number 8 on the indicator, but this one?
2. How to clear all digits on indicator?
3. How do I clear a single digit?

**Comment by Hossein-M98** [comment]
1. I think your seven-segment display is common-cathode type. Therefore, you must change seven-segment display type in 65th line of "TM1638.h" file. 
![Annotation 2021-07-01 141328](https://user-images.githubusercontent.com/52778819/124104635-b9e9c200-da77-11eb-8a8c-c5ece92edf20.png)

2. Add this function to your project and call it:
`void ClearAllDigits(void)
{
  uint8_t Buffer[8] = {0};
  TM1638_SetMultipleDigit(Buffer, 0, 8);
}`

3. `void ClearSingleDigit(uint8_t DigitNumber)
{
  TM1638_SetSingleDigit(0, DigitNumber);
}`
